development:
  uuid_prefix: {{cookiecutter.cluster_uuid}}
  secret_token: secrettoken
  blob_signing_key: blobsigningkey
  sso_app_secret: ssoappsecret
  sso_app_id: arvaos-server
  sso_provider_url: "https://sso"
  sso_insecure: true
  workbench_address: "https://workbench/"
  websocket_address: "wss://ws/websocket"
  git_repo_ssh_base: "git@git-httpd:"
  git_repo_https_base: "http://git-httpd/"
  new_users_are_active: true
  auto_admin_first_user: true
  auto_setup_new_users: true
  auto_setup_new_users_with_vm_uuid: vm_uuid
  auto_setup_new_users_with_repository: true
  default_collection_replication: 1
  docker_image_formats: ["v2"]
  keep_web_service_url: https://keep-web/
  ManagementToken: managementtoken

