# syntax=docker/dockerfile:experimental

# Initial crude image using packages, following
# https://doc.arvados.org/v1.4/install/install-compute-node.html

ARG COMPUTE_IMAGE
FROM ${COMPUTE_IMAGE} AS builder

ENV DEBIAN_FRONTEND noninteractive

ENV ARVADOS_API_HOST ${ARVADOS_API_HOST}
ENV ARVADOS_API_TOKEN ${ARVADOS_API_TOKEN}
ENV ARVADOS_API_HOST_INSECURE true


RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=cache-apt \
    --mount=type=cache,target=/var/lib/apt,sharing=locked,id=lib-apt \
    apt-get update \
 && apt-get --no-install-recommends install --yes gnupg \
 && /usr/bin/apt-key adv --keyserver keyserver.ubuntu.com --recv 1078ECD7 \
 && echo "deb http://apt.arvados.org/buster buster main" | tee /etc/apt/sources.list.d/arvados.list \
 && apt-get update \
 && apt-get install --yes \
                    --no-install-recommends \
                    libfuse2 \
                    python3-arvados-fuse \
                    arvados-docker-cleaner \
 && echo -n '#!/bin/sh\nexec /usr/bin/crunch-run -container-enable-networking=default -container-network-mode=host $@' |tee /usr/local/bin/crunch-run.sh \
 && chmod 755 /usr/local/bin/crunch-run.sh \
 && apt-get autoremove --purge --yes 

COPY --from=nmarvie/server /app/arvados-server /usr/local/bin/crunch-run

