# syntax=docker/dockerfile:experimental
# https://www.firehydrant.io/blog/developing-a-ruby-on-rails-app-with-docker-compose/
### BUILDER
FROM golang:buster AS builder

ARG APP_NAME
ARG APP_DIR

ENV DEBIAN_FRONTEND noninteractive

COPY ./arvados /usr/src/arvados/git.arvados.org/arvados.git/

# https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md
# RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=cache-apt \
    --mount=type=cache,target=/var/lib/apt,sharing=locked,id=lib-apt \
    apt-get update \
 && apt-get install --yes --no-install-recommends \
            git \
            libfuse-dev \
            libpam0g-dev

WORKDIR /usr/src/arvados/git.arvados.org/arvados.git

RUN --mount=type=cache,target=/root/.cache,id=root-cache \
    --mount=type=cache,target=/go/pkg,id=go-cache-pkg \
    go mod download

RUN --mount=type=cache,target=/root/.cache,id=root-cache \
    --mount=type=cache,target=/go/pkg,id=go-cache-pkg \
    GOOS=linux \
    go install -a -installsuffix cgo ./$APP_DIR/$APP_NAME

## This are development tools that we install when we use "target:" in docker
RUN --mount=type=cache,target=/root/.cache,id=root-cache \
    --mount=type=cache,target=/go/pkg,id=go-cache-pkg \
       go get github.com/uudashr/gopkgs/v2/cmd/gopkgs \
	&& go get github.com/ramya-rao-a/go-outline \
	&& go get github.com/cweill/gotests/... \
	&& go get github.com/fatih/gomodifytags \
	&& go get github.com/josharian/impl \
	&& go get github.com/haya14busa/goplay/cmd/goplay \
	&& go get github.com/go-delve/delve/cmd/dlv \
	&& go get golang.org/x/lint/golint \
	&& go get golang.org/x/tools/gopls

#FINAL IMAGE
FROM debian:buster-slim AS final

ARG APP_NAME

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=cache-apt \
    --mount=type=cache,target=/var/lib/apt,sharing=locked,id=lib-apt \
    apt-get update \
 && apt-get install --yes --no-install-recommends \
            libfuse2

WORKDIR /app/
COPY --from=builder /go/bin/$APP_NAME .
COPY configs/build/LAST_BUILD_INFO /BUILD_INFO
# Damn - https://github.com/moby/moby/issues/18492#issuecomment-347364597
RUN ln -s ./$APP_NAME executable
ENTRYPOINT ["./executable"]
