#!/bin/bash -x
# Check arvados/tools/arvbox/lib/arvbox/docker/api-setup.sh

set -euo pipefail

## if not specified will do 8004
PORT=${1:-8004}

export GEM_HOME=/cache/gem
export BUNDLE_PATH=/cache/gem
export NPM_CONFIG_PREFIX=/cache/npm

echo "Run bundle install if required"
bundle update --bundler || bundle install

echo "Waiting for the database server to be ready"
for t in {1..20}; do
  if pg_isready -h database; then
    echo "Database server ready"
    break
  fi
  echo "Database not ready..."
  sleep 1
done

echo "Try to create the database if it does not exist"
bundle exec rails db:version || bundle exec rails db:setup

echo "Run migrations to update/upgrade the database structure"
bundle exec rails db:migrate || exit 1

echo "Starting the Rails API server"
bundle exec rails server -b 0.0.0.0 -p ${PORT}
