#!/bin/bash -x
# Check arvados/tools/arvbox/lib/arvbox/docker/service/workbench/run-service

PORT=$1

export GEM_HOME=/cache/gem
export NPM_CONFIG_PREFIX=/cache/npm

echo "Run bundle install if required"
bundle update --bundler || bundle install

# Tried to add this to the Dockerfile, but the npm assets need the /etc/arvados/config.yml file in place
echo "Building and precompiling assets"
RAILS_GROUPS=assets bundle exec rake npm:install && \
RAILS_GROUPS=assets bundle exec rake assets:precompile

echo "Starting the workbench server"
bundle exec rails server -b 0.0.0.0 -p ${PORT}
